services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: exampledb
    ports:
      - 3036:3036
    volumes:
      - db_mysql:/var/lib/mysql
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: backend
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: exampledb
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    networks:
      - app-network
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge


volumes:
  db_mysql: